/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package PracticaVectores;
import org.junit.Test;
import static org.junit.Assert.*;

public class VectorTest {

  @Test public void testModulo() {
    Vector vector = new Vector(0,0,5,0);
    assertTrue(5 == vector.getModuloV());
  }

  // @Test public void testObtenerAngulo() {
  //   Vector vector = new Vector(0,0,3,3);
  //     assertTrue(45 == vector.getAngulo());
  // }

  @Test public void testAnguloDireccion() {
    Vector vector = new Vector(0,0,5,5);
    assertTrue(45 == vector.getAnguloDirec());
    // assertEquals(45, vector.getAnguloDirec(), 0,00001);
  }

  @Test public void testAnguloDireccionTrue() {
    Vector vector = new Vector(0,0,-5,5);
    assertTrue(135 == vector.getAnguloDirec());
  }
}
