package Ventana;

import java.awt.Image;
import java.util.ArrayList;
import javax.swing.Icon;
import javax.swing.ImageIcon;

public class VentanaEdicion extends javax.swing.JFrame {

    private UserManager userManag;
    private VentanaFormulario vFormulario;
    private Autenticacion autent;
    private ListUsuarios listUsers;
    
    public VentanaEdicion(UserManager newUserManag, Autenticacion newAutent, VentanaFormulario newVentanaFormulario, ListUsuarios listUsers) {
        initComponents();
        userManag = newUserManag;
        autent = newAutent;
        this.listUsers = listUsers;
        this.setLocationRelativeTo(null);
        ImageIcon imagen = new ImageIcon("src/imagenes/FData.jpg");
        Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(jLabel8.getWidth(), jLabel8.getHeight(), Image.SCALE_DEFAULT));
        jLabel8.setIcon(icono);
        this.repaint();
    }
    
//    public void setVentanaFormulario(VentanaFormulario newVentanaFormulario){
//        vFormulario = newVentanaFormulario;
//    }
    
    public VentanaEdicion getVentana(){
        return this;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        btnUserForm = new javax.swing.JButton();
        btnListUsers = new javax.swing.JButton();
        lblNombre = new javax.swing.JLabel();
        lblLastName = new javax.swing.JLabel();
        lblDireccion = new javax.swing.JLabel();
        lblSueldo = new javax.swing.JLabel();
        lblID = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Data Editor");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 160, 40));

        btnSearch.setBackground(new java.awt.Color(255, 255, 255));
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        getContentPane().add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, -1, -1));

        jTextField1.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 200, 30));

        jLabel2.setText("Data to search:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Exit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 20, -1, -1));

        btnUserForm.setText("User Form");
        btnUserForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserFormActionPerformed(evt);
            }
        });
        getContentPane().add(btnUserForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 360, -1, -1));

        btnListUsers.setText("List of Users");
        btnListUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListUsersActionPerformed(evt);
            }
        });
        getContentPane().add(btnListUsers, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, -1, -1));
        getContentPane().add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 90, 210));
        getContentPane().add(lblLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 80, 210));
        getContentPane().add(lblDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 90, 210));
        getContentPane().add(lblSueldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, 70, 210));
        getContentPane().add(lblID, new org.netbeans.lib.awtextra.AbsoluteConstraints(441, 140, 50, 210));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/FData.jpg"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        printDates(listUsers.searchAllUserData(jTextField1.getText()));
        this.repaint();
    }//GEN-LAST:event_btnSearchActionPerformed

    private void printDates(ArrayList<Usuario> list){
        String name ="", lastName="", sueldo="", ocupation="", numReg="";
        for (int i = 0; i < list.size(); i++) {
            name += "<p>"+list.get(i).getName();
            lastName += "<p>"+list.get(i).getLastName();
            numReg += "<p>"+list.get(i).getAge();
            ocupation += "<p>"+list.get(i).getDirection();
            sueldo += "<p>"+list.get(i).getSueldo();
        }
        lblNombre.setText("<html>Nombre"+name+"<html>");
        lblLastName.setText("<html>Apellido"+lastName+"<html>");
        lblDireccion.setText("<html>Cargo"+ocupation+"<html>");
        lblSueldo.setText("<html>Suedo"+sueldo+"<html>");
        lblID.setText("<html>Num de Reg."+numReg+"<html>");
    }
    
    private void btnListUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListUsersActionPerformed
        this.setVisible(false);
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaDatos(userManag.ShowUsers(), getVentana()).setVisible(true);
            }
        });
    }//GEN-LAST:event_btnListUsersActionPerformed

    private void btnUserFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserFormActionPerformed
        this.setVisible(false);
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                vFormulario.setVisible(true);
            }
        });
    }//GEN-LAST:event_btnUserFormActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnListUsers;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUserForm;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblSueldo;
    // End of variables declaration//GEN-END:variables
}
